package com.cyan.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="cartitem")
public class Cartitem {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="item_id")
	private Integer itemId;
	
	@Column(name="cart_id")
	private Integer cartId;
	
	@Column(name="product_Id")
	private Integer productId;
	
	@Column(name="price")
	private Double price;
	
	@Column(name="quantity")
	private Integer quantity;
	
	@Column(name="total")
	private Double total;

	
	
	
	
	public Integer getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartitem.item_id
	 * @param itemId  the value for cartitem.item_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartitem.cart_id
	 * @return  the value of cartitem.cart_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getCartId() {
		return cartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartitem.cart_id
	 * @param cartId  the value for cartitem.cart_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartitem.product_id
	 * @return  the value of cartitem.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartitem.product_id
	 * @param productId  the value for cartitem.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartitem.price
	 * @return  the value of cartitem.price
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartitem.price
	 * @param price  the value for cartitem.price
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartitem.quantity
	 * @return  the value of cartitem.quantity
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartitem.quantity
	 * @param quantity  the value for cartitem.quantity
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartitem.total
	 * @return  the value of cartitem.total
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Double getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartitem.total
	 * @param total  the value for cartitem.total
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setTotal(Double total) {
		this.total = total;
	}
}