package com.cyan.entity;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name="category")
public class Category {

	@Id
	@Column(name="category_id")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer categoryId;

	@Column(name="department_id")
	private Integer departmentId;

	@Column(name="category_name")
	private String categoryName;

	@Column(name="description")
	private String description;
	
	
	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
	@JoinColumn(name="category_id")
	private Set<Product> products;


	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.category_id
	 * @param categoryId  the value for category.category_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.department_id
	 * @return  the value of category.department_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.department_id
	 * @param departmentId  the value for category.department_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.category_name
	 * @return  the value of category.category_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.category_name
	 * @param categoryName  the value for category.category_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.description
	 * @return  the value of category.description
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.description
	 * @param description  the value for category.description
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}