package com.cyan.entity;

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name="customer")
public class Customer {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="user_id")
	private Integer userId;

	@Column(name="username")
	private String username;

	@Column(name="password")
	private String password;

	@Column(name="real_name")
	private String realName;

	@Column(name="phone")
	private String phone;

	@Column(name="email")
	private String email;

	@Column(name="address")
	private String address;

	@Column(name="zip")
	private String zip;

	@Column(name="receive_email")
	private Boolean receiveEmail;

	@Column(name="register_date")
	private Date registerDate;
	
	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
	@JoinColumn(name="user_id")
	private Set<Orders> orders;
	
	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
	@JoinColumn(name="user_id")
	private Set<Review> reviews;
	
	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
	@JoinColumn(name="user_id")
	private Set<Cart> carts;
	
	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
	@JoinColumn(name="user_id")
	private Set<Creditcard> creditcards;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.user_id
	 * @return  the value of customer.user_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.user_id
	 * @param userId  the value for customer.user_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.username
	 * @return  the value of customer.username
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.username
	 * @param username  the value for customer.username
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.password
	 * @return  the value of customer.password
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.password
	 * @param password  the value for customer.password
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.real_name
	 * @return  the value of customer.real_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.real_name
	 * @param realName  the value for customer.real_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.phone
	 * @return  the value of customer.phone
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.phone
	 * @param phone  the value for customer.phone
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.email
	 * @return  the value of customer.email
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.email
	 * @param email  the value for customer.email
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.address
	 * @return  the value of customer.address
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.address
	 * @param address  the value for customer.address
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.zip
	 * @return  the value of customer.zip
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.zip
	 * @param zip  the value for customer.zip
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.receive_email
	 * @return  the value of customer.receive_email
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Boolean getReceiveEmail() {
		return receiveEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.receive_email
	 * @param receiveEmail  the value for customer.receive_email
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setReceiveEmail(Boolean receiveEmail) {
		this.receiveEmail = receiveEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.register_date
	 * @return  the value of customer.register_date
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Date getRegisterDate() {
		return registerDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.register_date
	 * @param registerDate  the value for customer.register_date
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}
}