package com.cyan.entity;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name="Department")
public class Department {

	@Id
	@Column(name="department_id")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer departmentId;
	
	@Column(name="department_name")
	private String departmentName;
	
	@Column(name="description")
	private String description;
	
	
	@OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id")
	private Set<Category> categories;
	

	
	public Integer getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.department_id
	 * @param departmentId  the value for department.department_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.department_name
	 * @return  the value of department.department_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getDepartmentName() {
		return departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.department_name
	 * @param departmentName  the value for department.department_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.description
	 * @return  the value of department.description
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.description
	 * @param description  the value for department.description
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}