package com.cyan.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="employee")
public class Employee{

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="user_id")
	private Integer userId;

	@Column(name="username")
	private String username;

	@Column(name="password")
	private String password;

	@Column(name="real_name")
	private String realName;


	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.user_id
	 * @param userId  the value for employee.user_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.username
	 * @return  the value of employee.username
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.username
	 * @param username  the value for employee.username
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.password
	 * @return  the value of employee.password
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.password
	 * @param password  the value for employee.password
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.real_name
	 * @return  the value of employee.real_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.real_name
	 * @param realName  the value for employee.real_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}
}