package com.cyan.entity;

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@Entity
@Table(name="orders")
@JsonIgnoreProperties
public class Orders {
    
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="order_id")
    private Integer orderId;

	@Column(name="user_id")
    private Integer userId;

	@Column(name="order_date")
    private Date orderDate;

	@Column(name="order_status")
    private Byte orderStatus;

	@Column(name="order_sum")
    private Double orderSum;

	@Column(name="address")
    private String address;

	@Column(name="city")
    private String city;

	@Column(name="state")
    private String state;

	@Column(name="zip")
    private Integer zip;

	@Column(name="receiver_name")
    private String receiverName;

	@Column(name="email")
    private String email;

	@Column(name="phone")
    private String phone;


	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id")
	private Set<Orderdetail> details;

	
	
    public Set<Orderdetail> getDetails() {
		return details;
	}

	public void setDetails(Set<Orderdetail> details) {
		this.details = details;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_date
     *
     * @return the value of orders.order_date
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_date
     *
     * @param orderDate the value for orders.order_date
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_status
     *
     * @return the value of orders.order_status
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_status
     *
     * @param orderStatus the value for orders.order_status
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_sum
     *
     * @return the value of orders.order_sum
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Double getOrderSum() {
        return orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_sum
     *
     * @param orderSum the value for orders.order_sum
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setOrderSum(Double orderSum) {
        this.orderSum = orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.address
     *
     * @return the value of orders.address
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.address
     *
     * @param address the value for orders.address
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.city
     *
     * @return the value of orders.city
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.city
     *
     * @param city the value for orders.city
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.state
     *
     * @return the value of orders.state
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.state
     *
     * @param state the value for orders.state
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.zip
     *
     * @return the value of orders.zip
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Integer getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.zip
     *
     * @param zip the value for orders.zip
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setZip(Integer zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_name
     *
     * @return the value of orders.receiver_name
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_name
     *
     * @param receiverName the value for orders.receiver_name
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.email
     *
     * @return the value of orders.email
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.email
     *
     * @param email the value for orders.email
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.phone
     *
     * @return the value of orders.phone
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.phone
     *
     * @param phone the value for orders.phone
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}