package com.cyan.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name="payment")
public class Payment {


	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="payment_id")
	private Integer paymentId;

	@Column(name="card_id")
	private Integer cardId;

	@Column(name="order_id")
	private Integer orderId;

	@Column(name="payment_date")
	private Date paymentDate;


	
	
	public Integer getPaymentId() {
		return paymentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.payment_id
	 * @param paymentId  the value for payment.payment_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.card_id
	 * @return  the value of payment.card_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.card_id
	 * @param cardId  the value for payment.card_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.order_id
	 * @return  the value of payment.order_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.order_id
	 * @param orderId  the value for payment.order_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.payment_date
	 * @return  the value of payment.payment_date
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Date getPaymentDate() {
		return paymentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.payment_date
	 * @param paymentDate  the value for payment.payment_date
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}
}