package com.cyan.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="picture")
public class Picture {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="picture_id")
	private Integer pictureId;
	
	@Column(name="product_id")
	private Integer productId;
	
	@Column(name="picture_name")
	private String pictureName;
	
	@Column(name="path")
	private String path;

	
	
	public Integer getPictureId() {
		return pictureId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.picture_id
	 * @param pictureId  the value for picture.picture_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.product_id
	 * @return  the value of picture.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.product_id
	 * @param productId  the value for picture.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.picture_name
	 * @return  the value of picture.picture_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getPictureName() {
		return pictureName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.picture_name
	 * @param pictureName  the value for picture.picture_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPictureName(String pictureName) {
		this.pictureName = pictureName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.path
	 * @return  the value of picture.path
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.path
	 * @param path  the value for picture.path
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPath(String path) {
		this.path = path;
	}
}